version: '3.7'

services:
    app:
        build:
            context: .
        working_dir: /app
        volumes:
            - ./app:/app
        ports:
            - 9010:8080
        entrypoint:
            - http-server 
            - /app/dist